# This file was generated by GoReleaser. DO NOT EDIT.
cask "overseer" do
  version "0.22.0"

  on_macos do
    on_intel do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_darwin_amd64.tar.gz"
      sha256 "26844a5c4ba3dcccfc28af69e037ceb79ecdc6f404ffe27c09071154b0b388ab"
    end
    on_arm do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_darwin_arm64.tar.gz"
      sha256 "d1f42a4f9473053bb98e879a1c7740e452d836ca8e83d12a57f0e8fe8e2c0297"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_linux_amd64.tar.gz"
      sha256 "4367ea0ce19cb6e24f9b816fdbb9c9bd2a35e1a55a6f4c89f0332eca78c276e5"
    end
    on_arm do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_linux_arm64.tar.gz"
      sha256 "e82cbe276d37a2b07c7ccd330dac2539f21e064717a364728896afe2ce5621a5"
    end
  end

  name "overseer"
  desc "Personal CLI for environment setup and daily automation"
  homepage "https://github.com/arthurvasconcelos/overseer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "overseer"
  manpage "man/overseer-accounts.1"
  manpage "man/overseer-brain-git-init.1"
  manpage "man/overseer-brain-path.1"
  manpage "man/overseer-brain-pull.1"
  manpage "man/overseer-brain-push.1"
  manpage "man/overseer-brain-setup.1"
  manpage "man/overseer-brain-status.1"
  manpage "man/overseer-brain.1"
  manpage "man/overseer-brew-check.1"
  manpage "man/overseer-brew-dump.1"
  manpage "man/overseer-brew-install.1"
  manpage "man/overseer-brew.1"
  manpage "man/overseer-completion-bash.1"
  manpage "man/overseer-completion-fish.1"
  manpage "man/overseer-completion-powershell.1"
  manpage "man/overseer-completion-zsh.1"
  manpage "man/overseer-completion.1"
  manpage "man/overseer-config-schema.1"
  manpage "man/overseer-config.1"
  manpage "man/overseer-context.1"
  manpage "man/overseer-daily.1"
  manpage "man/overseer-docker-list.1"
  manpage "man/overseer-docker-use.1"
  manpage "man/overseer-docker.1"
  manpage "man/overseer-env-list.1"
  manpage "man/overseer-env-show.1"
  manpage "man/overseer-env-use.1"
  manpage "man/overseer-env.1"
  manpage "man/overseer-focus.1"
  manpage "man/overseer-git-branch.1"
  manpage "man/overseer-git-profile-add.1"
  manpage "man/overseer-git-profile-apply.1"
  manpage "man/overseer-git-profile-defaults.1"
  manpage "man/overseer-git-profile-edit.1"
  manpage "man/overseer-git-profile-list.1"
  manpage "man/overseer-git-profile-remove.1"
  manpage "man/overseer-git-profile.1"
  manpage "man/overseer-git-setup.1"
  manpage "man/overseer-git.1"
  manpage "man/overseer-kube-list.1"
  manpage "man/overseer-kube-use.1"
  manpage "man/overseer-kube.1"
  manpage "man/overseer-mcp.1"
  manpage "man/overseer-note-append.1"
  manpage "man/overseer-note-daily.1"
  manpage "man/overseer-note-new.1"
  manpage "man/overseer-note-search.1"
  manpage "man/overseer-note.1"
  manpage "man/overseer-notify.1"
  manpage "man/overseer-plugins-toggle.1"
  manpage "man/overseer-plugins.1"
  manpage "man/overseer-prs.1"
  manpage "man/overseer-repos-open.1"
  manpage "man/overseer-repos-pull.1"
  manpage "man/overseer-repos-search.1"
  manpage "man/overseer-repos-setup.1"
  manpage "man/overseer-repos-status.1"
  manpage "man/overseer-repos.1"
  manpage "man/overseer-run.1"
  manpage "man/overseer-setup.1"
  manpage "man/overseer-ssh-list.1"
  manpage "man/overseer-ssh-setup.1"
  manpage "man/overseer-ssh-show.1"
  manpage "man/overseer-ssh-use.1"
  manpage "man/overseer-ssh.1"
  manpage "man/overseer-standup.1"
  manpage "man/overseer-status.1"
  manpage "man/overseer-update.1"
  manpage "man/overseer-weekly.1"
  manpage "man/overseer.1"
  generate_completions_from_executable "overseer",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
