# This file was generated by GoReleaser. DO NOT EDIT.
cask "overseer" do
  version "0.20.1"

  on_macos do
    on_intel do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_darwin_amd64.tar.gz"
      sha256 "d1c7fa69976ff518d2737a48dfa5b1bce3fe851b0e14026801244ea460f5cc56"
    end
    on_arm do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_darwin_arm64.tar.gz"
      sha256 "191e60146791298a9215e284298ea1d676d516e62dc88d9cbb149996480d1fe6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_linux_amd64.tar.gz"
      sha256 "35839b7994a64fda78d2f693076b905ac02a6783f4c36c9e2121eedb54a86ccd"
    end
    on_arm do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_linux_arm64.tar.gz"
      sha256 "8ac71538fcc8c8ba46f10d0422ca9451aa69f939b3bff67c391af493cebba693"
    end
  end

  name "overseer"
  desc "Personal CLI for environment setup and daily automation"
  homepage "https://github.com/arthurvasconcelos/overseer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "overseer"
  manpage "man/overseer-accounts.1"
  manpage "man/overseer-brain-git-init.1"
  manpage "man/overseer-brain-path.1"
  manpage "man/overseer-brain-pull.1"
  manpage "man/overseer-brain-push.1"
  manpage "man/overseer-brain-setup.1"
  manpage "man/overseer-brain-status.1"
  manpage "man/overseer-brain.1"
  manpage "man/overseer-brew-check.1"
  manpage "man/overseer-brew-dump.1"
  manpage "man/overseer-brew-install.1"
  manpage "man/overseer-brew.1"
  manpage "man/overseer-completion-bash.1"
  manpage "man/overseer-completion-fish.1"
  manpage "man/overseer-completion-powershell.1"
  manpage "man/overseer-completion-zsh.1"
  manpage "man/overseer-completion.1"
  manpage "man/overseer-config-schema.1"
  manpage "man/overseer-config.1"
  manpage "man/overseer-context.1"
  manpage "man/overseer-daily.1"
  manpage "man/overseer-git-profile-add.1"
  manpage "man/overseer-git-profile-apply.1"
  manpage "man/overseer-git-profile-defaults.1"
  manpage "man/overseer-git-profile-edit.1"
  manpage "man/overseer-git-profile-list.1"
  manpage "man/overseer-git-profile-remove.1"
  manpage "man/overseer-git-profile.1"
  manpage "man/overseer-git-setup.1"
  manpage "man/overseer-git.1"
  manpage "man/overseer-mcp.1"
  manpage "man/overseer-note-daily.1"
  manpage "man/overseer-note-new.1"
  manpage "man/overseer-note-search.1"
  manpage "man/overseer-note.1"
  manpage "man/overseer-plugins-toggle.1"
  manpage "man/overseer-plugins.1"
  manpage "man/overseer-prs.1"
  manpage "man/overseer-repos-pull.1"
  manpage "man/overseer-repos-setup.1"
  manpage "man/overseer-repos-status.1"
  manpage "man/overseer-repos.1"
  manpage "man/overseer-run.1"
  manpage "man/overseer-setup.1"
  manpage "man/overseer-status.1"
  manpage "man/overseer-update.1"
  manpage "man/overseer.1"
  generate_completions_from_executable "overseer",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
