# This file was generated by GoReleaser. DO NOT EDIT.
cask "overseer" do
  version "0.20.0"

  on_macos do
    on_intel do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_darwin_amd64.tar.gz"
      sha256 "17d5ead8cfeca7228b9b6d767dd64970bf7cbed24daed4853aea23659323bc44"
    end
    on_arm do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_darwin_arm64.tar.gz"
      sha256 "36a0638a15a59ed00801befa458cfdaffe5f5d25493fa7cfb4039484434d7e4b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_linux_amd64.tar.gz"
      sha256 "66b25667d0358864fa2ca3c2c40654df8fe45c78e2e32b4214713187e6af48f2"
    end
    on_arm do
      url "https://github.com/arthurvasconcelos/overseer/releases/download/v#{version}/overseer_#{version}_linux_arm64.tar.gz"
      sha256 "ce6e969e69caf7153abd874fbc789c6e7caf859867593601092c7e19be65a85a"
    end
  end

  name "overseer"
  desc "Personal CLI for environment setup and daily automation"
  homepage "https://github.com/arthurvasconcelos/overseer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "overseer"
  manpage "man/overseer-accounts.1"
  manpage "man/overseer-brain-git-init.1"
  manpage "man/overseer-brain-path.1"
  manpage "man/overseer-brain-pull.1"
  manpage "man/overseer-brain-push.1"
  manpage "man/overseer-brain-setup.1"
  manpage "man/overseer-brain-status.1"
  manpage "man/overseer-brain.1"
  manpage "man/overseer-brew-check.1"
  manpage "man/overseer-brew-dump.1"
  manpage "man/overseer-brew-install.1"
  manpage "man/overseer-brew.1"
  manpage "man/overseer-completion-bash.1"
  manpage "man/overseer-completion-fish.1"
  manpage "man/overseer-completion-powershell.1"
  manpage "man/overseer-completion-zsh.1"
  manpage "man/overseer-completion.1"
  manpage "man/overseer-config-schema.1"
  manpage "man/overseer-config.1"
  manpage "man/overseer-context.1"
  manpage "man/overseer-daily.1"
  manpage "man/overseer-git-profile-add.1"
  manpage "man/overseer-git-profile-apply.1"
  manpage "man/overseer-git-profile-defaults.1"
  manpage "man/overseer-git-profile-edit.1"
  manpage "man/overseer-git-profile-list.1"
  manpage "man/overseer-git-profile-remove.1"
  manpage "man/overseer-git-profile.1"
  manpage "man/overseer-git-setup.1"
  manpage "man/overseer-git.1"
  manpage "man/overseer-mcp.1"
  manpage "man/overseer-note-daily.1"
  manpage "man/overseer-note-new.1"
  manpage "man/overseer-note-search.1"
  manpage "man/overseer-note.1"
  manpage "man/overseer-plugins-toggle.1"
  manpage "man/overseer-plugins.1"
  manpage "man/overseer-prs.1"
  manpage "man/overseer-repos-pull.1"
  manpage "man/overseer-repos-setup.1"
  manpage "man/overseer-repos-status.1"
  manpage "man/overseer-repos.1"
  manpage "man/overseer-run.1"
  manpage "man/overseer-setup.1"
  manpage "man/overseer-status.1"
  manpage "man/overseer-update.1"
  manpage "man/overseer.1"
  generate_completions_from_executable "overseer",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

end
